version: '3'
services:
  weather-data:
    image: "postgres"
    ports:
      - "5431:5431"
    env_file:
      - database.env
    volumes:
      # [PATH_TO_POSTGRES_DATA]:/var/lib/postgressql/data/
      - /Library/PostgreSQL/13/data/:/var/lib/postgressql/data/
  chainlink:
    image: "smartcontract/chainlink:0.10.12"
    env_file: .env
    depends_on:
      - weather-data
    ports:
      - "6688:6688"
    volumes:
      # [PATH_TO_REPO_CHAINLINK_VOLUME]:/chainlink/
      - /Users/rucreswe/chainlink-fun/chainlink-volume/:/chainlink/
    command: node start --password /chainlink/password.txt --api /chainlink/apicredentials.txt 